# Generated by Django 5.0.6 on 2024-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='New', max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('task_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
