# Generated by Django 5.0.6 on 2024-06-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
